// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
///
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpUWqlgIDRd-lUmyWM-RmfsfqqFjXH4vM',
    appId: '1:118469003907:web:a34b7b6a115f08cf4069b6',
    messagingSenderId: '118469003907',
    projectId: 'moneymonitor-1',
    authDomain: 'moneymonitor-1.firebaseapp.com',
    storageBucket: 'moneymonitor-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEbGDyset_NL_9nBad_kqaNzegjLzJdhQ',
    appId: '1:118469003907:android:8ec47798be9efaf34069b6',
    messagingSenderId: '118469003907',
    projectId: 'moneymonitor-1',
    storageBucket: 'moneymonitor-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVA3Rl3aKC9DK9_0tfV4zNIVbDsZei0ew',
    appId: '1:118469003907:ios:ac4208a493edf1f34069b6',
    messagingSenderId: '118469003907',
    projectId: 'moneymonitor-1',
    storageBucket: 'moneymonitor-1.firebasestorage.app',
    iosBundleId: 'com.moneyMonitor.app',
  );
}
